### ISSUE TITLE
chapter 4, exercise name

### ISSUE THREAD

**Issue by roxerto** [thejsway/thejsway_es#2]
I already finished the translation of the whole book, now I'm rereading each chapter trying to spot any kind of mistakes to fix them, while creating the correspondent Spanish screenshots or translating some pictures into Spanish. 

The first exercise in Chapter 4 is named Carousel, in my case I could not understand what exactly I had to do. I had to check the exercises section on GitHub to discover what this task is about. I think a simple exchange of words could solve this tiny issue, is there a problem if instead of Carousel, I name it something like "Turn manager"? I think this is more clear and relates to customer flow management.

**Comment by bpesquet** [comment]
Hi,
Thanks for your wonderful work. I shall update the presentation of the book to showcase its translations.
Regarding your question, "turn manager" is fine by me.
