### ISSUE TITLE
chapter 5 What "ones" means?

### ISSUE THREAD

**Issue by roxerto** [thejsway/thejsway_es#3]
There is a paragraph in Chapter 5 with the following content:

However, not everything deserves to be in its own function. It’s better to write short and focused
**ones**, in order to limit dependencies and improve program understanding.

I cannot fully understand, what the word "ones" is referring to? what is better? short and focused functions or short and focused statements?

**Comment by bpesquet** [comment]
It refers to the functions, that should be short and focused. This sentence is probably confusing, I might change it.
